export const fontOptions = [
  "Arial",
  "Verdana",
  "Times New Roman",
  "Courier New",
  "Verdana",
  "Tahoma",
  "Georgia",
  "Calibri",
  "Cambria",
  "Cursive",
  "Fantasy",
  "Monospace",
  "Serif",
  "Sans-serif",
  "System-ui",
  "Inherit",
  "Garamond",
  "Impact",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Trebuchet MS",
  "Lucida Sans",
  "Comic Sans MS",
  "Arial Black",
  "Arial Narrow",
  "Bookman Old Style",
  "Brush Script MT",
  "Century",
  "Century Gothic",
  "Century Schoolbook",
  "Copperplate",
  "Courier",
  "Geneva",
  "Georgia",
  "Helvetica",
  "Impact",
  "Papyrus",
  "Rockwell",
];
